# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jesse Cambon

author: 
  name: Jesse Cambon
  email: jesse.cambon@gmail.com

# Google analytics measurement id  
google_analytics: G-BHLL758SMS

description: Musings on data and open source software
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jessecambon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#github_username: jessecambon
#linkedin_username: jessecambon
#twitter_username: JesseCambon

header_pages:
  - about.md
  - resources.md
 # - test.md

# Build settings
markdown: kramdown

minima:
  date_format: "%b %-d %Y"

  social_links:
    github:  jessecambon
    twitter: JesseCambon
    linkedin: jessecambon

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

highlighter: rouge

# Files jekyll should ignore when building
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - "*.Rmd"
  - "*.Rproj"
  - rmd_config.R
  - .RProj.user

show_excerpts: true # show post excerpts

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: jessecambon
